random_state: 42

model:
  batch_size: 2048
  epochs: 100
  learning_rate: 0.001
  optimizer: Adam
  activation_function: relu
  shuffle: True
  conv_layers:
    - in_channels: 1
      out_channels: 32
      kernel_size: 3
      stride: 1
      padding: 1
    - in_channels: 32
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
  pool_layers:
    - kernel_size: 2
      stride: 2
      padding: 0
    - kernel_size: 2
      stride: 2
      padding: 0
  view_shape:
    channels: 64
    height: 7
    width: 7
  fc1:
    in_features: 'As per view_shape (channels * height * width)'
    out_features: 128
  fc2:
    in_features: 128
    out_features: 10
  dropout:
    p: 0.5

evaluation:
  train: True
  test: True
  epoch_frequency: 1
  shuffle: True

logging:
  log_to_wandb: False
  project_name: 'mnist_cnn'
