random_state: 42

model:
  shuffle: True
  batch_size: 1024
  epochs: 40
  learning_rate: 0.001
  optimizer: Adam
  activation_function: tanh
  conv_layers:
    - type: Conv2d
      in_channels: 1
      out_channels: 32
      kernel_size: 3
      stride: 1
      padding: 1
    - type: BatchNorm2d
      num_features: 32
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
      padding: 0
    - type: Conv2d
      in_channels: 32
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
    - type: BatchNorm2d
      num_features: 64
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
      padding: 0
  view_shape:
    channels: 64
    height: 7
    width: 7
  fc_layers:
    - type: Linear
      in_features: 3136
      out_features: 128
    - type: LayerNorm
      normalized_shape: 128
    - type: Dropout
      p: 0.5
    - type: Linear
      in_features: 128
      out_features: 64
    - type: LayerNorm
      normalized_shape: 64
    - type: Dropout
      p: 0.5
    - type: Linear
      in_features: 64
      out_features: 10

evaluation:
  train: True
  test: True
  epoch_frequency: 1
  shuffle: True

cross_validation:
  tune: False
  k_folds: 5
  shuffle: True
  metric_to_optimize: average_accuracy
  param_grid:
    shuffle: [True]
    batch_size: [2048]
    epochs: [40]
    learning_rate: [0.001]
    optimizer: [Adam]
    activation_function: [tanh]
    dropout: [0.20]

logging:
  log_to_wandb: True
  project_name: 'mnist_cnn'
