random_state: 42

model:
  shuffle: True
  batch_size: 2048
  epochs: 10
  learning_rate: 0.001
  optimizer: Adam
  activation_function: relu
  conv_layers:
    - in_channels: 1
      out_channels: 32
      kernel_size: 3
      stride: 1
      padding: 1
    - in_channels: 32
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
  pool_layers:
    - kernel_size: 2
      stride: 2
      padding: 0
    - kernel_size: 2
      stride: 2
      padding: 0
  view_shape:
    channels: 64
    height: 7
    width: 7
  fc_layers:
    - out_features: 128
      dropout: 0.5
    - out_features: 64
      dropout: 0.5
    - out_features: 10
      dropout: 0.0

evaluation:
  train: True
  test: True
  epoch_frequency: 1
  shuffle: True

cross_validation:
  k_folds: 3
  shuffle: True
  metric_to_optimize: average_accuracy
  param_grid:
    shuffle: [True]
    batch_size: [2048]
    epochs: [5]
    learning_rate: [0.001]
    optimizer: [Adam]
    activation_function: [relu]
    dropout: [0.0, 0.3]

logging:
  log_to_wandb: False
  project_name: 'mnist_cnn'
