random_state: 42

model:
  batch_size: 128
  epochs: 100
  optimizer: Adam
  learning_rate: 0.001
  activation_function: relu
  conv1:
    in_channels: 1
    out_channels: 32
    kernel_size: 3
    stride: 1
    padding: 1
  conv2:
    in_channels: 32
    out_channels: 64
    kernel_size: 3
    stride: 1
    padding: 1
  pool1:
    kernel_size: 2
    stride: 2
    padding: 0
  pool2:
    kernel_size: 2
    stride: 2
    padding: 0
  view_shape:
    channels: 64
    height: 7
    width: 7
  fc1:
    in_features: 'As per view_shape (channels * height * width)'
    out_features: 128
  fc2:
    in_features: 128
    out_features: 10
  dropout:
    p: 0.5

